/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */

/**
 *
 * @author Lenovo
 */
public class DashboardPengajuPanel extends javax.swing.JPanel {

    /**
     * Creates new form DashboardPengajuPanel
     */
    public DashboardPengajuPanel() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        loginLabel = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();
        judulDashboardLabel = new javax.swing.JLabel();
        subjudulPengajuanLabel = new javax.swing.JLabel();
        subjudulPengajuanLabel1 = new javax.swing.JLabel();
        subjudulPengajuanLabel2 = new javax.swing.JLabel();
        buatAjuanButton = new javax.swing.JButton();
        lihatRiwayatButton = new javax.swing.JButton();
        lihatKalenderButton = new javax.swing.JButton();

        setBackground(new java.awt.Color(245, 255, 251));

        loginLabel.setFont(new java.awt.Font("Segoe UI", 1, 16)); // NOI18N
        loginLabel.setForeground(new java.awt.Color(39, 67, 32));
        loginLabel.setText("Dashboard");

        jPanel1.setBackground(new java.awt.Color(39, 67, 32));
        jPanel1.setPreferredSize(new java.awt.Dimension(210, 120));

        judulDashboardLabel.setBackground(new java.awt.Color(245, 255, 251));
        judulDashboardLabel.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        judulDashboardLabel.setForeground(new java.awt.Color(245, 255, 251));
        judulDashboardLabel.setText("Proses Pengajuan");

        subjudulPengajuanLabel.setBackground(new java.awt.Color(245, 255, 251));
        subjudulPengajuanLabel.setFont(new java.awt.Font("Segoe UI", 0, 10)); // NOI18N
        subjudulPengajuanLabel.setForeground(new java.awt.Color(245, 255, 251));
        subjudulPengajuanLabel.setText("Menunggu Verifikasi Administrator");

        subjudulPengajuanLabel1.setBackground(new java.awt.Color(245, 255, 251));
        subjudulPengajuanLabel1.setFont(new java.awt.Font("Segoe UI", 0, 8)); // NOI18N
        subjudulPengajuanLabel1.setForeground(new java.awt.Color(245, 255, 251));
        subjudulPengajuanLabel1.setText("17 Agustus 20XX, XX:XX -- XX:XX WIB");

        subjudulPengajuanLabel2.setBackground(new java.awt.Color(245, 255, 251));
        subjudulPengajuanLabel2.setFont(new java.awt.Font("Segoe UI", 0, 8)); // NOI18N
        subjudulPengajuanLabel2.setForeground(new java.awt.Color(245, 255, 251));
        subjudulPengajuanLabel2.setText("Aula X");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(judulDashboardLabel)
                    .addComponent(subjudulPengajuanLabel)
                    .addComponent(subjudulPengajuanLabel1)
                    .addComponent(subjudulPengajuanLabel2))
                .addContainerGap(51, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(judulDashboardLabel)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(subjudulPengajuanLabel)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(subjudulPengajuanLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(subjudulPengajuanLabel2)
                .addContainerGap(73, Short.MAX_VALUE))
        );

        buatAjuanButton.setBackground(new java.awt.Color(188, 237, 90));
        buatAjuanButton.setText("Buat Ajuan Baru");

        lihatRiwayatButton.setBackground(new java.awt.Color(188, 237, 90));
        lihatRiwayatButton.setText("Lihat Riwayat Ajuan");

        lihatKalenderButton.setBackground(new java.awt.Color(188, 237, 90));
        lihatKalenderButton.setText("Lihat Kalender");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(13, 13, 13)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(loginLabel)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(buatAjuanButton, javax.swing.GroupLayout.PREFERRED_SIZE, 66, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(lihatRiwayatButton, javax.swing.GroupLayout.PREFERRED_SIZE, 66, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(lihatKalenderButton, javax.swing.GroupLayout.PREFERRED_SIZE, 66, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(13, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(45, 45, 45)
                .addComponent(loginLabel)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 149, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(buatAjuanButton, javax.swing.GroupLayout.PREFERRED_SIZE, 66, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lihatRiwayatButton, javax.swing.GroupLayout.PREFERRED_SIZE, 66, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lihatKalenderButton, javax.swing.GroupLayout.PREFERRED_SIZE, 66, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(200, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton buatAjuanButton;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JLabel judulDashboardLabel;
    private javax.swing.JButton lihatKalenderButton;
    private javax.swing.JButton lihatRiwayatButton;
    private javax.swing.JLabel loginLabel;
    private javax.swing.JLabel subjudulPengajuanLabel;
    private javax.swing.JLabel subjudulPengajuanLabel1;
    private javax.swing.JLabel subjudulPengajuanLabel2;
    // End of variables declaration//GEN-END:variables
}
