package edu.praktikumpbo.tugaskelompok1;

/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */

/**
 *
 * @author Lenovo
 */
public class FormEksternalPanel extends javax.swing.JPanel {

    /**
     * Creates new form FormEksternalPanel
     */
    public FormEksternalPanel() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        loginLabel = new javax.swing.JLabel();
        judulDashboardLabel = new javax.swing.JLabel();
        subjudulPengajuanLabel1 = new javax.swing.JLabel();
        subjudulPengajuanLabel2 = new javax.swing.JLabel();
        subjudulPengajuanLabel3 = new javax.swing.JLabel();
        subjudulPengajuanLabel4 = new javax.swing.JLabel();
        subjudulPengajuanLabel5 = new javax.swing.JLabel();
        subjudulPengajuanLabel6 = new javax.swing.JLabel();
        subjudulPengajuanLabel7 = new javax.swing.JLabel();
        subjudulPengajuanLabel8 = new javax.swing.JLabel();
        judulDashboardLabel1 = new javax.swing.JLabel();
        subjudulPengajuanLabel9 = new javax.swing.JLabel();
        jTextField1 = new javax.swing.JTextField();
        jTextField2 = new javax.swing.JTextField();
        subjudulPengajuanLabel10 = new javax.swing.JLabel();
        jTextField3 = new javax.swing.JTextField();
        jTextField4 = new javax.swing.JTextField();
        subjudulPengajuanLabel11 = new javax.swing.JLabel();
        subjudulPengajuanLabel12 = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();
        judulDashboardLabel2 = new javax.swing.JLabel();
        jToggleButton1 = new javax.swing.JToggleButton();
        jToggleButton5 = new javax.swing.JToggleButton();
        jToggleButton6 = new javax.swing.JToggleButton();
        jToggleButton7 = new javax.swing.JToggleButton();
        jToggleButton8 = new javax.swing.JToggleButton();
        jToggleButton9 = new javax.swing.JToggleButton();
        judulDashboardLabel3 = new javax.swing.JLabel();
        jTextField5 = new javax.swing.JTextField();
        judulDashboardLabel4 = new javax.swing.JLabel();
        jButton2 = new javax.swing.JButton();
        judulDashboardLabel5 = new javax.swing.JLabel();
        jButton3 = new javax.swing.JButton();
        judulDashboardLabel6 = new javax.swing.JLabel();
        jCheckBox1 = new javax.swing.JCheckBox();
        subjudulPengajuanLabel13 = new javax.swing.JLabel();
        jTextField6 = new javax.swing.JTextField();
        jCheckBox2 = new javax.swing.JCheckBox();
        jCheckBox3 = new javax.swing.JCheckBox();
        jCheckBox4 = new javax.swing.JCheckBox();
        loginButton = new javax.swing.JButton();
        loginButton1 = new javax.swing.JButton();

        setBackground(new java.awt.Color(245, 255, 251));

        loginLabel.setFont(new java.awt.Font("Segoe UI", 1, 16)); // NOI18N
        loginLabel.setForeground(new java.awt.Color(39, 67, 32));
        loginLabel.setText("Buat Ajuan Baru");

        judulDashboardLabel.setBackground(new java.awt.Color(245, 255, 251));
        judulDashboardLabel.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        judulDashboardLabel.setForeground(new java.awt.Color(39, 67, 32));
        judulDashboardLabel.setText("Data Pengaju");

        subjudulPengajuanLabel1.setBackground(new java.awt.Color(245, 255, 251));
        subjudulPengajuanLabel1.setFont(new java.awt.Font("Segoe UI", 0, 10)); // NOI18N
        subjudulPengajuanLabel1.setForeground(new java.awt.Color(39, 67, 32));
        subjudulPengajuanLabel1.setText("Nama");

        subjudulPengajuanLabel2.setBackground(new java.awt.Color(245, 255, 251));
        subjudulPengajuanLabel2.setFont(new java.awt.Font("Segoe UI", 0, 10)); // NOI18N
        subjudulPengajuanLabel2.setForeground(new java.awt.Color(39, 67, 32));
        subjudulPengajuanLabel2.setText("NIM");

        subjudulPengajuanLabel3.setBackground(new java.awt.Color(245, 255, 251));
        subjudulPengajuanLabel3.setFont(new java.awt.Font("Segoe UI", 0, 10)); // NOI18N
        subjudulPengajuanLabel3.setForeground(new java.awt.Color(39, 67, 32));
        subjudulPengajuanLabel3.setText("Nomor Telepon");

        subjudulPengajuanLabel4.setBackground(new java.awt.Color(245, 255, 251));
        subjudulPengajuanLabel4.setFont(new java.awt.Font("Segoe UI", 0, 10)); // NOI18N
        subjudulPengajuanLabel4.setForeground(new java.awt.Color(39, 67, 32));
        subjudulPengajuanLabel4.setText("Email");

        subjudulPengajuanLabel5.setBackground(new java.awt.Color(245, 255, 251));
        subjudulPengajuanLabel5.setFont(new java.awt.Font("Segoe UI", 1, 10)); // NOI18N
        subjudulPengajuanLabel5.setForeground(new java.awt.Color(39, 67, 32));
        subjudulPengajuanLabel5.setText("NamaPengaju");

        subjudulPengajuanLabel6.setBackground(new java.awt.Color(245, 255, 251));
        subjudulPengajuanLabel6.setFont(new java.awt.Font("Segoe UI", 1, 10)); // NOI18N
        subjudulPengajuanLabel6.setForeground(new java.awt.Color(39, 67, 32));
        subjudulPengajuanLabel6.setText("123456890");

        subjudulPengajuanLabel7.setBackground(new java.awt.Color(245, 255, 251));
        subjudulPengajuanLabel7.setFont(new java.awt.Font("Segoe UI", 1, 10)); // NOI18N
        subjudulPengajuanLabel7.setForeground(new java.awt.Color(39, 67, 32));
        subjudulPengajuanLabel7.setText("123456890");

        subjudulPengajuanLabel8.setBackground(new java.awt.Color(245, 255, 251));
        subjudulPengajuanLabel8.setFont(new java.awt.Font("Segoe UI", 1, 10)); // NOI18N
        subjudulPengajuanLabel8.setForeground(new java.awt.Color(39, 67, 32));
        subjudulPengajuanLabel8.setText("emailpengaju@abc.com");

        judulDashboardLabel1.setBackground(new java.awt.Color(245, 255, 251));
        judulDashboardLabel1.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        judulDashboardLabel1.setForeground(new java.awt.Color(39, 67, 32));
        judulDashboardLabel1.setText("Tanggal Pengajuan ");

        subjudulPengajuanLabel9.setBackground(new java.awt.Color(245, 255, 251));
        subjudulPengajuanLabel9.setFont(new java.awt.Font("Segoe UI", 0, 8)); // NOI18N
        subjudulPengajuanLabel9.setForeground(new java.awt.Color(39, 67, 32));
        subjudulPengajuanLabel9.setText("Jam");

        jTextField1.setFont(new java.awt.Font("Segoe UI", 0, 10)); // NOI18N
        jTextField1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField1ActionPerformed(evt);
            }
        });

        jTextField2.setFont(new java.awt.Font("Segoe UI", 0, 10)); // NOI18N
        jTextField2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField2ActionPerformed(evt);
            }
        });

        subjudulPengajuanLabel10.setBackground(new java.awt.Color(245, 255, 251));
        subjudulPengajuanLabel10.setFont(new java.awt.Font("Segoe UI", 0, 8)); // NOI18N
        subjudulPengajuanLabel10.setForeground(new java.awt.Color(39, 67, 32));
        subjudulPengajuanLabel10.setText("Tanggal");

        jTextField3.setFont(new java.awt.Font("Segoe UI", 0, 10)); // NOI18N
        jTextField3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField3ActionPerformed(evt);
            }
        });

        jTextField4.setFont(new java.awt.Font("Segoe UI", 0, 10)); // NOI18N
        jTextField4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField4ActionPerformed(evt);
            }
        });

        subjudulPengajuanLabel11.setBackground(new java.awt.Color(245, 255, 251));
        subjudulPengajuanLabel11.setFont(new java.awt.Font("Segoe UI", 0, 8)); // NOI18N
        subjudulPengajuanLabel11.setForeground(new java.awt.Color(39, 67, 32));
        subjudulPengajuanLabel11.setText("Bulan");

        subjudulPengajuanLabel12.setBackground(new java.awt.Color(245, 255, 251));
        subjudulPengajuanLabel12.setFont(new java.awt.Font("Segoe UI", 0, 8)); // NOI18N
        subjudulPengajuanLabel12.setForeground(new java.awt.Color(39, 67, 32));
        subjudulPengajuanLabel12.setText("Tahun");

        jButton1.setBackground(new java.awt.Color(188, 237, 90));

        judulDashboardLabel2.setBackground(new java.awt.Color(245, 255, 251));
        judulDashboardLabel2.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        judulDashboardLabel2.setForeground(new java.awt.Color(39, 67, 32));
        judulDashboardLabel2.setText("Aula yang Dipinjam");

        jToggleButton1.setBackground(new java.awt.Color(188, 237, 90));
        jToggleButton1.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jToggleButton1.setForeground(new java.awt.Color(39, 67, 32));
        jToggleButton1.setText("1");
        jToggleButton1.setPreferredSize(new java.awt.Dimension(25, 25));

        jToggleButton5.setBackground(new java.awt.Color(188, 237, 90));
        jToggleButton5.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jToggleButton5.setForeground(new java.awt.Color(39, 67, 32));
        jToggleButton5.setText("2");
        jToggleButton5.setPreferredSize(new java.awt.Dimension(25, 25));
        jToggleButton5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jToggleButton5ActionPerformed(evt);
            }
        });

        jToggleButton6.setBackground(new java.awt.Color(188, 237, 90));
        jToggleButton6.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jToggleButton6.setForeground(new java.awt.Color(39, 67, 32));
        jToggleButton6.setText("3");
        jToggleButton6.setPreferredSize(new java.awt.Dimension(25, 25));

        jToggleButton7.setBackground(new java.awt.Color(188, 237, 90));
        jToggleButton7.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jToggleButton7.setForeground(new java.awt.Color(39, 67, 32));
        jToggleButton7.setText("4");
        jToggleButton7.setPreferredSize(new java.awt.Dimension(25, 25));

        jToggleButton8.setBackground(new java.awt.Color(167, 81, 66));
        jToggleButton8.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jToggleButton8.setForeground(new java.awt.Color(245, 255, 251));
        jToggleButton8.setText("5");
        jToggleButton8.setPreferredSize(new java.awt.Dimension(25, 25));

        jToggleButton9.setBackground(new java.awt.Color(188, 237, 90));
        jToggleButton9.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jToggleButton9.setForeground(new java.awt.Color(39, 67, 32));
        jToggleButton9.setText("6");
        jToggleButton9.setPreferredSize(new java.awt.Dimension(25, 25));

        judulDashboardLabel3.setBackground(new java.awt.Color(245, 255, 251));
        judulDashboardLabel3.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        judulDashboardLabel3.setForeground(new java.awt.Color(39, 67, 32));
        judulDashboardLabel3.setText("Tujuan Peminjaman");

        jTextField5.setBackground(new java.awt.Color(245, 255, 251));
        jTextField5.setFont(new java.awt.Font("Segoe UI", 0, 10)); // NOI18N

        judulDashboardLabel4.setBackground(new java.awt.Color(245, 255, 251));
        judulDashboardLabel4.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        judulDashboardLabel4.setForeground(new java.awt.Color(39, 67, 32));
        judulDashboardLabel4.setText("Berkas Surat Izin Kegiatan");

        jButton2.setBackground(new java.awt.Color(245, 255, 251));
        jButton2.setFont(new java.awt.Font("Segoe UI", 0, 10)); // NOI18N
        jButton2.setText("Upload surat izin digital (pdf)");
        jButton2.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));

        judulDashboardLabel5.setBackground(new java.awt.Color(245, 255, 251));
        judulDashboardLabel5.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        judulDashboardLabel5.setForeground(new java.awt.Color(39, 67, 32));
        judulDashboardLabel5.setText("Berkas Data Diri (KTP)");

        jButton3.setBackground(new java.awt.Color(245, 255, 251));
        jButton3.setFont(new java.awt.Font("Segoe UI", 0, 10)); // NOI18N
        jButton3.setText("Upload KTP digital (pdf)");
        jButton3.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });

        judulDashboardLabel6.setBackground(new java.awt.Color(245, 255, 251));
        judulDashboardLabel6.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        judulDashboardLabel6.setForeground(new java.awt.Color(39, 67, 32));
        judulDashboardLabel6.setText("Fasilitas yang Diperlukan");

        jCheckBox1.setFont(new java.awt.Font("Segoe UI", 1, 10)); // NOI18N
        jCheckBox1.setForeground(new java.awt.Color(39, 67, 32));
        jCheckBox1.setText("Kursi");
        jCheckBox1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jCheckBox1ActionPerformed(evt);
            }
        });

        subjudulPengajuanLabel13.setBackground(new java.awt.Color(245, 255, 251));
        subjudulPengajuanLabel13.setFont(new java.awt.Font("Segoe UI", 0, 8)); // NOI18N
        subjudulPengajuanLabel13.setForeground(new java.awt.Color(39, 67, 32));
        subjudulPengajuanLabel13.setText("Nominal");

        jTextField6.setFont(new java.awt.Font("Segoe UI", 0, 10)); // NOI18N
        jTextField6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField6ActionPerformed(evt);
            }
        });

        jCheckBox2.setFont(new java.awt.Font("Segoe UI", 1, 10)); // NOI18N
        jCheckBox2.setForeground(new java.awt.Color(39, 67, 32));
        jCheckBox2.setText("Projektor");
        jCheckBox2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jCheckBox2ActionPerformed(evt);
            }
        });

        jCheckBox3.setFont(new java.awt.Font("Segoe UI", 1, 10)); // NOI18N
        jCheckBox3.setForeground(new java.awt.Color(39, 67, 32));
        jCheckBox3.setText("Papan Tulis");
        jCheckBox3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jCheckBox3ActionPerformed(evt);
            }
        });

        jCheckBox4.setFont(new java.awt.Font("Segoe UI", 1, 10)); // NOI18N
        jCheckBox4.setForeground(new java.awt.Color(39, 67, 32));
        jCheckBox4.setText("Meja");
        jCheckBox4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jCheckBox4ActionPerformed(evt);
            }
        });

        loginButton.setBackground(new java.awt.Color(188, 237, 90));
        loginButton.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        loginButton.setForeground(new java.awt.Color(39, 67, 32));
        loginButton.setText("Kirim Ajuan");

        loginButton1.setBackground(new java.awt.Color(188, 237, 90));
        loginButton1.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        loginButton1.setForeground(new java.awt.Color(39, 67, 32));
        loginButton1.setText("Edit");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(13, 13, 13)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(loginButton1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                        .addComponent(loginButton, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jCheckBox2)
                        .addGroup(layout.createSequentialGroup()
                            .addGap(21, 21, 21)
                            .addComponent(subjudulPengajuanLabel13)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                            .addComponent(jTextField6))
                        .addComponent(jCheckBox1)
                        .addComponent(judulDashboardLabel6)
                        .addComponent(judulDashboardLabel5)
                        .addComponent(jButton2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(judulDashboardLabel4)
                        .addComponent(jTextField5)
                        .addComponent(judulDashboardLabel3)
                        .addComponent(judulDashboardLabel2)
                        .addComponent(judulDashboardLabel1)
                        .addComponent(judulDashboardLabel)
                        .addComponent(loginLabel)
                        .addGroup(layout.createSequentialGroup()
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(subjudulPengajuanLabel1)
                                .addComponent(subjudulPengajuanLabel2))
                            .addGap(66, 66, 66)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(subjudulPengajuanLabel5)
                                .addComponent(subjudulPengajuanLabel6)))
                        .addGroup(layout.createSequentialGroup()
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(subjudulPengajuanLabel3)
                                .addComponent(subjudulPengajuanLabel4))
                            .addGap(23, 23, 23)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(subjudulPengajuanLabel7)
                                .addComponent(subjudulPengajuanLabel8)))
                        .addGroup(layout.createSequentialGroup()
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(jTextField1, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(subjudulPengajuanLabel9))
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addGroup(layout.createSequentialGroup()
                                    .addComponent(jTextField2, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                    .addComponent(jTextField3, javax.swing.GroupLayout.PREFERRED_SIZE, 55, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGroup(layout.createSequentialGroup()
                                    .addComponent(subjudulPengajuanLabel10)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                    .addComponent(subjudulPengajuanLabel11)))
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(subjudulPengajuanLabel12)
                                .addComponent(jTextField4, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                            .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGroup(layout.createSequentialGroup()
                            .addComponent(jToggleButton1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                            .addComponent(jToggleButton5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                            .addComponent(jToggleButton6, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                            .addComponent(jToggleButton7, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                            .addComponent(jToggleButton8, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                            .addComponent(jToggleButton9, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addComponent(jButton3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jCheckBox3)
                        .addComponent(jCheckBox4)))
                .addContainerGap(13, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(45, 45, 45)
                .addComponent(loginLabel)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(judulDashboardLabel)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(subjudulPengajuanLabel1)
                    .addComponent(subjudulPengajuanLabel5))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(subjudulPengajuanLabel2)
                    .addComponent(subjudulPengajuanLabel6))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(subjudulPengajuanLabel3)
                    .addComponent(subjudulPengajuanLabel7))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(subjudulPengajuanLabel4)
                    .addComponent(subjudulPengajuanLabel8))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(loginButton1)
                .addGap(15, 15, 15)
                .addComponent(judulDashboardLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(subjudulPengajuanLabel9)
                            .addComponent(subjudulPengajuanLabel10)
                            .addComponent(subjudulPengajuanLabel11)
                            .addComponent(subjudulPengajuanLabel12))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jTextField1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jTextField2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jTextField3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jTextField4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(judulDashboardLabel2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jToggleButton1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jToggleButton5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jToggleButton6, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jToggleButton7, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jToggleButton8, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jToggleButton9, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(judulDashboardLabel3)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jTextField5, javax.swing.GroupLayout.PREFERRED_SIZE, 66, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(judulDashboardLabel4)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jButton2, javax.swing.GroupLayout.PREFERRED_SIZE, 169, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(judulDashboardLabel5)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jButton3, javax.swing.GroupLayout.PREFERRED_SIZE, 169, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(judulDashboardLabel6)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jCheckBox1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(subjudulPengajuanLabel13)
                    .addComponent(jTextField6, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jCheckBox2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jCheckBox3)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jCheckBox4)
                .addGap(18, 18, 18)
                .addComponent(loginButton)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void jTextField1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField1ActionPerformed

    private void jTextField2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField2ActionPerformed

    private void jTextField3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField3ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField3ActionPerformed

    private void jTextField4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField4ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField4ActionPerformed

    private void jToggleButton5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jToggleButton5ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jToggleButton5ActionPerformed

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jButton3ActionPerformed

    private void jCheckBox1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jCheckBox1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jCheckBox1ActionPerformed

    private void jTextField6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField6ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField6ActionPerformed

    private void jCheckBox2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jCheckBox2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jCheckBox2ActionPerformed

    private void jCheckBox3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jCheckBox3ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jCheckBox3ActionPerformed

    private void jCheckBox4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jCheckBox4ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jCheckBox4ActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JCheckBox jCheckBox1;
    private javax.swing.JCheckBox jCheckBox2;
    private javax.swing.JCheckBox jCheckBox3;
    private javax.swing.JCheckBox jCheckBox4;
    private javax.swing.JTextField jTextField1;
    private javax.swing.JTextField jTextField2;
    private javax.swing.JTextField jTextField3;
    private javax.swing.JTextField jTextField4;
    private javax.swing.JTextField jTextField5;
    private javax.swing.JTextField jTextField6;
    private javax.swing.JToggleButton jToggleButton1;
    private javax.swing.JToggleButton jToggleButton5;
    private javax.swing.JToggleButton jToggleButton6;
    private javax.swing.JToggleButton jToggleButton7;
    private javax.swing.JToggleButton jToggleButton8;
    private javax.swing.JToggleButton jToggleButton9;
    private javax.swing.JLabel judulDashboardLabel;
    private javax.swing.JLabel judulDashboardLabel1;
    private javax.swing.JLabel judulDashboardLabel2;
    private javax.swing.JLabel judulDashboardLabel3;
    private javax.swing.JLabel judulDashboardLabel4;
    private javax.swing.JLabel judulDashboardLabel5;
    private javax.swing.JLabel judulDashboardLabel6;
    private javax.swing.JButton loginButton;
    private javax.swing.JButton loginButton1;
    private javax.swing.JLabel loginLabel;
    private javax.swing.JLabel subjudulPengajuanLabel1;
    private javax.swing.JLabel subjudulPengajuanLabel10;
    private javax.swing.JLabel subjudulPengajuanLabel11;
    private javax.swing.JLabel subjudulPengajuanLabel12;
    private javax.swing.JLabel subjudulPengajuanLabel13;
    private javax.swing.JLabel subjudulPengajuanLabel2;
    private javax.swing.JLabel subjudulPengajuanLabel3;
    private javax.swing.JLabel subjudulPengajuanLabel4;
    private javax.swing.JLabel subjudulPengajuanLabel5;
    private javax.swing.JLabel subjudulPengajuanLabel6;
    private javax.swing.JLabel subjudulPengajuanLabel7;
    private javax.swing.JLabel subjudulPengajuanLabel8;
    private javax.swing.JLabel subjudulPengajuanLabel9;
    // End of variables declaration//GEN-END:variables
}
