package edu.praktikumpbo.tugaskelompok1;

/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */

/**
 *
 * @author Lenovo
 */

public class KalenderPanel extends BasePanel {

    /**
     * Creates new form KalenderPanel
     */
    public KalenderPanel(SistemFrame frame) {
        super(frame);
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        loginLabel = new javax.swing.JLabel();
        javax.swing.JPanel bulanTahunPanel = new RoundedPanel(20, 20);
        judulDashboardLabel1 = new javax.swing.JLabel();
        tanggalPanel = new RoundedPanel(20, 20);
        jPanel3 = new javax.swing.JPanel();
        judulDashboardLabel = new javax.swing.JLabel();

        setBackground(new java.awt.Color(245, 255, 251));

        loginLabel.setFont(new java.awt.Font("Segoe UI", 1, 16)); // NOI18N
        loginLabel.setForeground(new java.awt.Color(39, 67, 32));
        loginLabel.setText("Kalender Penggunaan Aula");

        bulanTahunPanel.setBackground(new java.awt.Color(188, 237, 90));

        judulDashboardLabel1.setBackground(new java.awt.Color(167, 81, 66));
        judulDashboardLabel1.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        judulDashboardLabel1.setForeground(new java.awt.Color(39, 67, 32));
        judulDashboardLabel1.setText("Agustus 20XX");

        javax.swing.GroupLayout bulanTahunPanelLayout = new javax.swing.GroupLayout(bulanTahunPanel);
        bulanTahunPanel.setLayout(bulanTahunPanelLayout);
        bulanTahunPanelLayout.setHorizontalGroup(
            bulanTahunPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(bulanTahunPanelLayout.createSequentialGroup()
                .addGap(68, 68, 68)
                .addComponent(judulDashboardLabel1)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        bulanTahunPanelLayout.setVerticalGroup(
            bulanTahunPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, bulanTahunPanelLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(judulDashboardLabel1)
                .addContainerGap())
        );

        tanggalPanel.setBackground(new java.awt.Color(188, 237, 90));

        javax.swing.GroupLayout tanggalPanelLayout = new javax.swing.GroupLayout(tanggalPanel);
        tanggalPanel.setLayout(tanggalPanelLayout);
        tanggalPanelLayout.setHorizontalGroup(
            tanggalPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 215, Short.MAX_VALUE)
        );
        tanggalPanelLayout.setVerticalGroup(
            tanggalPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 165, Short.MAX_VALUE)
        );

        jPanel3.setBackground(new java.awt.Color(245, 255, 251));

        judulDashboardLabel.setBackground(new java.awt.Color(167, 81, 66));
        judulDashboardLabel.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        judulDashboardLabel.setForeground(new java.awt.Color(167, 81, 66));
        judulDashboardLabel.setText("Penggunaan Agustus 20XX");

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addComponent(judulDashboardLabel)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(judulDashboardLabel)
                .addContainerGap(102, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(13, 13, 13)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(loginLabel)
                    .addComponent(bulanTahunPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(tanggalPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jPanel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap(12, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(45, 45, 45)
                .addComponent(loginLabel)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(bulanTahunPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(tanggalPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jPanel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel jPanel3;
    private javax.swing.JLabel judulDashboardLabel;
    private javax.swing.JLabel judulDashboardLabel1;
    private javax.swing.JLabel loginLabel;
    private javax.swing.JPanel tanggalPanel;
    // End of variables declaration//GEN-END:variables
}
