package edu.praktikumpbo.tugaskelompok1;

/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */

/**
 *
 * @author Lenovo
 */
public class RiwayatPanel extends BasePanel {

    /**
     * Creates new form KalenderPanel
     */
    public RiwayatPanel(SistemFrame frame) {
        super(frame);
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        loginLabel = new javax.swing.JLabel();
        jComboBox1 = new javax.swing.JComboBox<>();
        jComboBox2 = new javax.swing.JComboBox<>();
        riwayat1Panel = new RoundedPanel(20,20);
        judulDashboardLabel = new javax.swing.JLabel();
        subjudulPengajuanLabel1 = new javax.swing.JLabel();
        subjudulPengajuanLabel2 = new javax.swing.JLabel();
        batalkanButton = new RoundedButton("Batalkan Ajuan", 30, 30);
        riwayat2Panel = new RoundedPanel(20,20);
        judulDashboardLabel1 = new javax.swing.JLabel();
        subjudulPengajuanLabel3 = new javax.swing.JLabel();
        subjudulPengajuanLabel4 = new javax.swing.JLabel();
        riwayat3Panel = new RoundedPanel(20,20);
        judulDashboardLabel2 = new javax.swing.JLabel();
        subjudulPengajuanLabel5 = new javax.swing.JLabel();
        subjudulPengajuanLabel6 = new javax.swing.JLabel();
        riwayat4Panel = new RoundedPanel(20,20);
        judulDashboardLabel3 = new javax.swing.JLabel();
        subjudulPengajuanLabel7 = new javax.swing.JLabel();
        subjudulPengajuanLabel8 = new javax.swing.JLabel();
        navigatorPanel = new javax.swing.JPanel();

        setBackground(new java.awt.Color(245, 255, 251));

        loginLabel.setFont(new java.awt.Font("Segoe UI", 1, 16)); // NOI18N
        loginLabel.setForeground(new java.awt.Color(39, 67, 32));
        loginLabel.setText("Riwayat Ajuan");

        jComboBox1.setBackground(new java.awt.Color(245, 255, 251));
        jComboBox1.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Dari Terbaru", "Dari Terlama" }));

        jComboBox2.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Semua", "Dalam Proses", "Diterima", "Ditolak", "Dibatalkan" }));

        riwayat1Panel.setBackground(new java.awt.Color(245, 255, 251));
        riwayat1Panel.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        riwayat1Panel.setPreferredSize(new java.awt.Dimension(210, 100));

        judulDashboardLabel.setBackground(new java.awt.Color(245, 255, 251));
        judulDashboardLabel.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        judulDashboardLabel.setForeground(new java.awt.Color(39, 67, 32));
        judulDashboardLabel.setText("17 Agustus XXXX - Aula X ");

        subjudulPengajuanLabel1.setBackground(new java.awt.Color(255, 255, 255));
        subjudulPengajuanLabel1.setFont(new java.awt.Font("Segoe UI", 0, 8)); // NOI18N
        subjudulPengajuanLabel1.setForeground(new java.awt.Color(39, 67, 32));
        subjudulPengajuanLabel1.setText("Jam     : XX:XX--XX:XX WIB");

        subjudulPengajuanLabel2.setBackground(new java.awt.Color(255, 255, 255));
        subjudulPengajuanLabel2.setFont(new java.awt.Font("Segoe UI", 0, 8)); // NOI18N
        subjudulPengajuanLabel2.setForeground(new java.awt.Color(39, 67, 32));
        subjudulPengajuanLabel2.setText("Status : Menunggu verifikasi administrator");

        batalkanButton.setBackground(new java.awt.Color(167, 81, 66));
        batalkanButton.setFont(new java.awt.Font("Segoe UI", 1, 10)); // NOI18N
        batalkanButton.setForeground(new java.awt.Color(245, 255, 251));
        batalkanButton.setText("Batalkan Ajuan");

        javax.swing.GroupLayout riwayat1PanelLayout = new javax.swing.GroupLayout(riwayat1Panel);
        riwayat1Panel.setLayout(riwayat1PanelLayout);
        riwayat1PanelLayout.setHorizontalGroup(
            riwayat1PanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(riwayat1PanelLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(riwayat1PanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(batalkanButton, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(riwayat1PanelLayout.createSequentialGroup()
                        .addGroup(riwayat1PanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(judulDashboardLabel)
                            .addComponent(subjudulPengajuanLabel1)
                            .addComponent(subjudulPengajuanLabel2))
                        .addGap(0, 50, Short.MAX_VALUE)))
                .addContainerGap())
        );
        riwayat1PanelLayout.setVerticalGroup(
            riwayat1PanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(riwayat1PanelLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(judulDashboardLabel)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(subjudulPengajuanLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(subjudulPengajuanLabel2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 8, Short.MAX_VALUE)
                .addComponent(batalkanButton)
                .addContainerGap())
        );

        riwayat2Panel.setBackground(new java.awt.Color(188, 237, 90));
        riwayat2Panel.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        riwayat2Panel.setPreferredSize(new java.awt.Dimension(210, 100));

        judulDashboardLabel1.setBackground(new java.awt.Color(245, 255, 251));
        judulDashboardLabel1.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        judulDashboardLabel1.setForeground(new java.awt.Color(39, 67, 32));
        judulDashboardLabel1.setText("17 Agustus XXXX - Aula X ");

        subjudulPengajuanLabel3.setBackground(new java.awt.Color(255, 255, 255));
        subjudulPengajuanLabel3.setFont(new java.awt.Font("Segoe UI", 0, 8)); // NOI18N
        subjudulPengajuanLabel3.setForeground(new java.awt.Color(39, 67, 32));
        subjudulPengajuanLabel3.setText("Jam     : XX:XX--XX:XX WIB");

        subjudulPengajuanLabel4.setBackground(new java.awt.Color(255, 255, 255));
        subjudulPengajuanLabel4.setFont(new java.awt.Font("Segoe UI", 0, 8)); // NOI18N
        subjudulPengajuanLabel4.setForeground(new java.awt.Color(39, 67, 32));
        subjudulPengajuanLabel4.setText("Status : Ajuan diterima administrator");

        javax.swing.GroupLayout riwayat2PanelLayout = new javax.swing.GroupLayout(riwayat2Panel);
        riwayat2Panel.setLayout(riwayat2PanelLayout);
        riwayat2PanelLayout.setHorizontalGroup(
            riwayat2PanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(riwayat2PanelLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(riwayat2PanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(judulDashboardLabel1)
                    .addComponent(subjudulPengajuanLabel3)
                    .addComponent(subjudulPengajuanLabel4))
                .addContainerGap(58, Short.MAX_VALUE))
        );
        riwayat2PanelLayout.setVerticalGroup(
            riwayat2PanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(riwayat2PanelLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(judulDashboardLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(subjudulPengajuanLabel3)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(subjudulPengajuanLabel4)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        riwayat3Panel.setBackground(new java.awt.Color(39, 67, 32));
        riwayat3Panel.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        riwayat3Panel.setPreferredSize(new java.awt.Dimension(210, 100));

        judulDashboardLabel2.setBackground(new java.awt.Color(245, 255, 251));
        judulDashboardLabel2.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        judulDashboardLabel2.setForeground(new java.awt.Color(245, 255, 251));
        judulDashboardLabel2.setText("17 Agustus XXXX - Aula X ");

        subjudulPengajuanLabel5.setBackground(new java.awt.Color(245, 255, 251));
        subjudulPengajuanLabel5.setFont(new java.awt.Font("Segoe UI", 0, 8)); // NOI18N
        subjudulPengajuanLabel5.setForeground(new java.awt.Color(245, 255, 251));
        subjudulPengajuanLabel5.setText("Jam     : XX:XX--XX:XX WIB");

        subjudulPengajuanLabel6.setBackground(new java.awt.Color(255, 255, 255));
        subjudulPengajuanLabel6.setFont(new java.awt.Font("Segoe UI", 0, 8)); // NOI18N
        subjudulPengajuanLabel6.setForeground(new java.awt.Color(245, 255, 251));
        subjudulPengajuanLabel6.setText("Status : Ajuan dibatalkan");

        javax.swing.GroupLayout riwayat3PanelLayout = new javax.swing.GroupLayout(riwayat3Panel);
        riwayat3Panel.setLayout(riwayat3PanelLayout);
        riwayat3PanelLayout.setHorizontalGroup(
            riwayat3PanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(riwayat3PanelLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(riwayat3PanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(judulDashboardLabel2)
                    .addComponent(subjudulPengajuanLabel5)
                    .addComponent(subjudulPengajuanLabel6))
                .addContainerGap(58, Short.MAX_VALUE))
        );
        riwayat3PanelLayout.setVerticalGroup(
            riwayat3PanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(riwayat3PanelLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(judulDashboardLabel2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(subjudulPengajuanLabel5)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(subjudulPengajuanLabel6)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        riwayat4Panel.setBackground(new java.awt.Color(167, 81, 66));
        riwayat4Panel.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        riwayat4Panel.setPreferredSize(new java.awt.Dimension(210, 100));

        judulDashboardLabel3.setBackground(new java.awt.Color(245, 255, 251));
        judulDashboardLabel3.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        judulDashboardLabel3.setForeground(new java.awt.Color(245, 255, 251));
        judulDashboardLabel3.setText("17 Agustus XXXX - Aula X ");

        subjudulPengajuanLabel7.setBackground(new java.awt.Color(245, 255, 251));
        subjudulPengajuanLabel7.setFont(new java.awt.Font("Segoe UI", 0, 8)); // NOI18N
        subjudulPengajuanLabel7.setForeground(new java.awt.Color(245, 255, 251));
        subjudulPengajuanLabel7.setText("Jam     : XX:XX--XX:XX WIB");

        subjudulPengajuanLabel8.setBackground(new java.awt.Color(255, 255, 255));
        subjudulPengajuanLabel8.setFont(new java.awt.Font("Segoe UI", 0, 8)); // NOI18N
        subjudulPengajuanLabel8.setForeground(new java.awt.Color(245, 255, 251));
        subjudulPengajuanLabel8.setText("Status : Ajuan ditolak pembina");

        javax.swing.GroupLayout riwayat4PanelLayout = new javax.swing.GroupLayout(riwayat4Panel);
        riwayat4Panel.setLayout(riwayat4PanelLayout);
        riwayat4PanelLayout.setHorizontalGroup(
            riwayat4PanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(riwayat4PanelLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(riwayat4PanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(judulDashboardLabel3)
                    .addComponent(subjudulPengajuanLabel7)
                    .addComponent(subjudulPengajuanLabel8))
                .addContainerGap(58, Short.MAX_VALUE))
        );
        riwayat4PanelLayout.setVerticalGroup(
            riwayat4PanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(riwayat4PanelLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(judulDashboardLabel3)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(subjudulPengajuanLabel7)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(subjudulPengajuanLabel8)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        navigatorPanel.setBackground(new java.awt.Color(188, 237, 90));

        javax.swing.GroupLayout navigatorPanelLayout = new javax.swing.GroupLayout(navigatorPanel);
        navigatorPanel.setLayout(navigatorPanelLayout);
        navigatorPanelLayout.setHorizontalGroup(
            navigatorPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );
        navigatorPanelLayout.setVerticalGroup(
            navigatorPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 35, Short.MAX_VALUE)
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(13, 13, 13)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(loginLabel)
                    .addComponent(riwayat1Panel, javax.swing.GroupLayout.PREFERRED_SIZE, 214, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jComboBox1, javax.swing.GroupLayout.PREFERRED_SIZE, 103, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jComboBox2, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addComponent(riwayat2Panel, javax.swing.GroupLayout.PREFERRED_SIZE, 214, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(riwayat3Panel, javax.swing.GroupLayout.PREFERRED_SIZE, 214, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(riwayat4Panel, javax.swing.GroupLayout.PREFERRED_SIZE, 214, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(12, Short.MAX_VALUE))
            .addComponent(navigatorPanel, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(navigatorPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(10, 10, 10)
                .addComponent(loginLabel)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jComboBox1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jComboBox2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(riwayat1Panel, javax.swing.GroupLayout.PREFERRED_SIZE, 93, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(riwayat2Panel, javax.swing.GroupLayout.PREFERRED_SIZE, 62, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(riwayat3Panel, javax.swing.GroupLayout.PREFERRED_SIZE, 62, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(riwayat4Panel, javax.swing.GroupLayout.PREFERRED_SIZE, 62, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(78, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton batalkanButton;
    private javax.swing.JComboBox<String> jComboBox1;
    private javax.swing.JComboBox<String> jComboBox2;
    private javax.swing.JLabel judulDashboardLabel;
    private javax.swing.JLabel judulDashboardLabel1;
    private javax.swing.JLabel judulDashboardLabel2;
    private javax.swing.JLabel judulDashboardLabel3;
    private javax.swing.JLabel loginLabel;
    private javax.swing.JPanel navigatorPanel;
    private javax.swing.JPanel riwayat1Panel;
    private javax.swing.JPanel riwayat2Panel;
    private javax.swing.JPanel riwayat3Panel;
    private javax.swing.JPanel riwayat4Panel;
    private javax.swing.JLabel subjudulPengajuanLabel1;
    private javax.swing.JLabel subjudulPengajuanLabel2;
    private javax.swing.JLabel subjudulPengajuanLabel3;
    private javax.swing.JLabel subjudulPengajuanLabel4;
    private javax.swing.JLabel subjudulPengajuanLabel5;
    private javax.swing.JLabel subjudulPengajuanLabel6;
    private javax.swing.JLabel subjudulPengajuanLabel7;
    private javax.swing.JLabel subjudulPengajuanLabel8;
    // End of variables declaration//GEN-END:variables
}
